version: "3.1"
services:
  postgresqldb:
    image: postgres:14.4
    container_name: pajs-backend
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata
volumes:
  dbdata:
